#!/bin/bash
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# commit-msg hook: Adds the projects name of the commited files to the commit message.

# Constants
COMMIT_MESSAGE_FILEPATH=$1
PROJECTS=("BigQueryWorkloadTester")

# Functions
function get_projects_touched_in_files(){
  files=$@
  project_headers=""
  
  for file in ${files}
  do
    file_header=$(get_project_from_filepath ${file})
    project_headers="${project_headers} ${file_header}"
  done

  # One-liner voodoo to return unique headers in single line format
  echo $(echo -e "${project_headers// /\\n}" | sort -u)
}

function get_project_from_filepath(){
  # If file does not have a known project we assume it to be related to root
  project_header="[Root]" 
  file=$1
  
  for project in ${PROJECTS[@]}
  do
   if [[ "${file}" == *"${project}"* ]]; then
          project_header="[${project}]"
    fi
  done
  
  echo "${project_header}"
 }  

# Main
COMMIT_MESSAGE=`cat ${COMMIT_MESSAGE_FILEPATH}`
MODIFIED_FILES=`git diff --cached --name-only`

COMMIT_MESSAGE_PROJECT_HEADERS=$(get_projects_touched_in_files ${MODIFIED_FILES})
COMMIT_MESSAGE_WITH_PROJECT_HEADERS="${COMMIT_MESSAGE_PROJECT_HEADERS} ${COMMIT_MESSAGE}"

echo "${COMMIT_MESSAGE_WITH_PROJECT_HEADERS}" > "${COMMIT_MESSAGE_FILEPATH}"

