#!/bin/bash
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Git pre-commit script that will run Google's Java Formatter and fail if files need to be re-formatted

# Check for google-java-format installation
if [ -z ${GOOGLE_JAVA_FORMAT_HOME+x} ];
  then echo "GOOGLE_JAVA_FORMAT_HOME is unset"
       exit 1;
fi

# Get Java files to be committed
MODIFIED_FILES=`git diff --cached --name-only -- '*.java'`

# Run the formatter
GOOGLE_JAVA_FORMAT_OUTPUT=`java -jar $GOOGLE_JAVA_FORMAT_HOME --set-exit-if-changed $MODIFIED_FILES`
GOOGLE_JAVA_FORMAT_EXIT_STATUS=$?

# TODO(ldanielmadariaga): Handle different verbosity levels
if [ $GOOGLE_JAVA_FORMAT_EXIT_STATUS -eq 1 ]
  then echo "$GOOGLE_JAVA_FORMAT_OUTPUT"
    exit 1;
  else
    exit 0;
fi

