#!/bin/bash
# Copyright 2018 The Pontem Authors. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Performs pylint on code being committed.
#
echo "Starting pre-commit"
# Check if pylint is available
pylint_version=`pip freeze | grep pylint\=`
if [ -z "$pylint_version" ]
then
  echo "pylint missing"
  exit 1;
else
  echo "Running ${pylint_version/==/' version '}"
fi

# get all files
files=`git diff --name-only --cached '*.py'`
if [ ${#files[@]} -eq 0 ]; then
  echo "No python files to lint"
else
  declare -A root_module_folders

  for f in $files
  do
    project_root=`echo ${f} | cut -d '/' -f1-1`
    root_module_path=`echo ${f} | cut -d '/' -f1-2`
    root_module_folders[$root_module_path]=$project_root
  done
  for root_module_folder in "${!root_module_folders[@]}"
  do
    echo "Processing $root_module_folder..."
    pylint --rcfile ${root_module_folders[$root_module_folder]}/pylintrc $root_module_folder
  done
fi
