steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/GoogleCloudPlatform/pontem.git']
    id: 'clone-repo'
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "$(ls .)"']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pontem-mysql-external-master/pontem-csr', '.', '-f', 'CloudSQLReplicator/container/Dockerfile']
    id: 'build-container'
    waitFor: ['clone-repo']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/pontem-mysql-external-master/pontem-csr']
    waitFor: ['build-container']
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 660s
images: ['gcr.io/pontem-mysql-external-master/pontem-csr']